//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the cob_kuka_xmlkrc package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __cob_kuka_xmlkrc__COB_KUKA_XMLKRCCONFIG_H__
#define __cob_kuka_xmlkrc__COB_KUKA_XMLKRCCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace cob_kuka_xmlkrc
{
  class cob_kuka_xmlkrcConfigStatics;
  
  class cob_kuka_xmlkrcConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(cob_kuka_xmlkrcConfig &config, const cob_kuka_xmlkrcConfig &max, const cob_kuka_xmlkrcConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const cob_kuka_xmlkrcConfig &config1, const cob_kuka_xmlkrcConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, cob_kuka_xmlkrcConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const cob_kuka_xmlkrcConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, cob_kuka_xmlkrcConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const cob_kuka_xmlkrcConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T cob_kuka_xmlkrcConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (cob_kuka_xmlkrcConfig::* field);

      virtual void clamp(cob_kuka_xmlkrcConfig &config, const cob_kuka_xmlkrcConfig &max, const cob_kuka_xmlkrcConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const cob_kuka_xmlkrcConfig &config1, const cob_kuka_xmlkrcConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, cob_kuka_xmlkrcConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const cob_kuka_xmlkrcConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, cob_kuka_xmlkrcConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const cob_kuka_xmlkrcConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 8 "../cfg/cob_kuka_xmlkrc.cfg"
      std::string KRC_ip_address;
//#line 9 "../cfg/cob_kuka_xmlkrc.cfg"
      int KRC_ip_port;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("cob_kuka_xmlkrcConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const cob_kuka_xmlkrcConfig &__max__ = __getMax__();
      const cob_kuka_xmlkrcConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const cob_kuka_xmlkrcConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const cob_kuka_xmlkrcConfig &__getDefault__();
    static const cob_kuka_xmlkrcConfig &__getMax__();
    static const cob_kuka_xmlkrcConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const cob_kuka_xmlkrcConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void cob_kuka_xmlkrcConfig::ParamDescription<std::string>::clamp(cob_kuka_xmlkrcConfig &config, const cob_kuka_xmlkrcConfig &max, const cob_kuka_xmlkrcConfig &min) const
  {
    return;
  }

  class cob_kuka_xmlkrcConfigStatics
  {
    friend class cob_kuka_xmlkrcConfig;
    
    cob_kuka_xmlkrcConfigStatics()
    {
//#line 8 "../cfg/cob_kuka_xmlkrc.cfg"
      __min__.KRC_ip_address = "";
//#line 8 "../cfg/cob_kuka_xmlkrc.cfg"
      __max__.KRC_ip_address = "";
//#line 8 "../cfg/cob_kuka_xmlkrc.cfg"
      __default__.KRC_ip_address = "127.0.0.1";
//#line 8 "../cfg/cob_kuka_xmlkrc.cfg"
      __param_descriptions__.push_back(cob_kuka_xmlkrcConfig::AbstractParamDescriptionConstPtr(new cob_kuka_xmlkrcConfig::ParamDescription<std::string>("KRC_ip_address", "str", 0, "Autogenerated parameter based on model.", "", &cob_kuka_xmlkrcConfig::KRC_ip_address)));
//#line 9 "../cfg/cob_kuka_xmlkrc.cfg"
      __min__.KRC_ip_port = 0;
//#line 9 "../cfg/cob_kuka_xmlkrc.cfg"
      __max__.KRC_ip_port = 100;
//#line 9 "../cfg/cob_kuka_xmlkrc.cfg"
      __default__.KRC_ip_port = 4444;
//#line 9 "../cfg/cob_kuka_xmlkrc.cfg"
      __param_descriptions__.push_back(cob_kuka_xmlkrcConfig::AbstractParamDescriptionConstPtr(new cob_kuka_xmlkrcConfig::ParamDescription<int>("KRC_ip_port", "int", 0, "Autogenerated parameter based on model.", "", &cob_kuka_xmlkrcConfig::KRC_ip_port)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<cob_kuka_xmlkrcConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<cob_kuka_xmlkrcConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    cob_kuka_xmlkrcConfig __max__;
    cob_kuka_xmlkrcConfig __min__;
    cob_kuka_xmlkrcConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const cob_kuka_xmlkrcConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static cob_kuka_xmlkrcConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &cob_kuka_xmlkrcConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const cob_kuka_xmlkrcConfig &cob_kuka_xmlkrcConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const cob_kuka_xmlkrcConfig &cob_kuka_xmlkrcConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const cob_kuka_xmlkrcConfig &cob_kuka_xmlkrcConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<cob_kuka_xmlkrcConfig::AbstractParamDescriptionConstPtr> &cob_kuka_xmlkrcConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const cob_kuka_xmlkrcConfigStatics *cob_kuka_xmlkrcConfig::__get_statics__()
  {
    const static cob_kuka_xmlkrcConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = cob_kuka_xmlkrcConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __COB_KUKA_XMLKRCRECONFIGURATOR_H__

