#define TAG_RECV_MSG_ID "Robot/MsgID"
#define TAG_RECV_CONFIRM "Robot/ConfirmTag"
#define TAG_RECV_SUB_ID "Robot/SubID"
#define TAG_RECV_ACTPOS "Robot/CurPos"
#define TAG_RECV_SLOT1 "Robot/Slot1"
#define TAG_RECV_SLOT2 "Robot/Slot2"
#define TAG_RECV_SLOT3 "Robot/Slot3"
#define TAG_RECV_RUN_POINTER "Robot/RunPointer"
#define TAG_RECV_RECV_POINTER "Robot/RecvPointer"

#define TAG_SEND_MSG_ID "Ext/MsgID"
#define TAG_SEND_SUB_ID "Ext/SubID"
#define TAG_SEND_PARAM1 "Ext/Param1"
#define TAG_SEND_PARAM2 "Ext/Param2"
#define TAG_SEND_FRAME "Ext/Frame"
#define TAG_SEND_AXIS "Ext/Axis"
#define TAG_SEND_LINVEL "Ext/LinVel"
#define TAG_SEND_AXVEL "Ext/AxVel"
